-- NetaTrack India: Phase 1 Migration 004
-- Promises and Projects Tables

CREATE TABLE IF NOT EXISTS `promises` (
    `id`                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `leader_id`         INT UNSIGNED   NOT NULL,
    `title`             VARCHAR(500)   NOT NULL,
    `description`       TEXT           DEFAULT NULL,
    `category`          VARCHAR(100)   DEFAULT NULL,
    `source_url`        VARCHAR(500)   DEFAULT NULL,
    `source_type`       ENUM('manifesto','speech','tweet','interview','official','other') DEFAULT 'other',
    `promised_date`     DATE           DEFAULT NULL,
    `deadline`          DATE           DEFAULT NULL,
    `status`            ENUM('pending','kept','broken','partial','in_progress','fake') DEFAULT 'pending',
    `completion_percent`TINYINT UNSIGNED DEFAULT 0,
    `ai_verified`       TINYINT(1)     DEFAULT 0,
    `ai_confidence`     DECIMAL(5,2)   DEFAULT 0,
    `admin_verified`    TINYINT(1)     DEFAULT 0,
    `fake_claim`        TINYINT(1)     DEFAULT 0,
    `fake_reason`       TEXT           DEFAULT NULL,
    `evidence_url`      VARCHAR(500)   DEFAULT NULL,
    `state_id`          INT UNSIGNED   DEFAULT NULL,
    `party_id`          INT UNSIGNED   DEFAULT NULL,
    `created_at`        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`leader_id`) REFERENCES `leaders`(`id`) ON DELETE CASCADE,
    INDEX `idx_leader`  (`leader_id`),
    INDEX `idx_status`  (`status`),
    INDEX `idx_category`(`category`),
    FULLTEXT INDEX `ft_search` (`title`,`description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `projects` (
    `id`                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `title`               VARCHAR(500)   NOT NULL,
    `slug`                VARCHAR(520)   NOT NULL UNIQUE,
    `description`         TEXT           DEFAULT NULL,
    `category`            VARCHAR(100)   DEFAULT NULL,
    `state_id`            INT UNSIGNED   DEFAULT NULL,
    `leader_id`           INT UNSIGNED   DEFAULT NULL,
    `party_id`            INT UNSIGNED   DEFAULT NULL,
    `budget_allocated`    DECIMAL(15,2)  DEFAULT 0,
    `budget_used`         DECIMAL(15,2)  DEFAULT 0,
    `budget_currency`     VARCHAR(10)    DEFAULT 'INR',
    `start_date`          DATE           DEFAULT NULL,
    `expected_end_date`   DATE           DEFAULT NULL,
    `actual_end_date`     DATE           DEFAULT NULL,
    `status`              ENUM('planned','in_progress','completed','delayed','cancelled','stalled') DEFAULT 'planned',
    `completion_percent`  TINYINT UNSIGNED DEFAULT 0,
    `delay_days`          INT            DEFAULT 0,
    `tender_number`       VARCHAR(200)   DEFAULT NULL,
    `source_url`          VARCHAR(500)   DEFAULT NULL,
    `beneficiaries`       VARCHAR(200)   DEFAULT NULL,
    `ai_verified`         TINYINT(1)     DEFAULT 0,
    `admin_verified`      TINYINT(1)     DEFAULT 0,
    `is_featured`         TINYINT(1)     DEFAULT 0,
    `latitude`            DECIMAL(10,7)  DEFAULT NULL,
    `longitude`           DECIMAL(10,7)  DEFAULT NULL,
    `created_at`          DATETIME       DEFAULT CURRENT_TIMESTAMP,
    `updated_at`          DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`state_id`)  REFERENCES `states`(`id`)   ON DELETE SET NULL,
    FOREIGN KEY (`leader_id`) REFERENCES `leaders`(`id`)  ON DELETE SET NULL,
    FOREIGN KEY (`party_id`)  REFERENCES `parties`(`id`)  ON DELETE SET NULL,
    INDEX `idx_slug`    (`slug`),
    INDEX `idx_state`   (`state_id`),
    INDEX `idx_status`  (`status`),
    INDEX `idx_leader`  (`leader_id`),
    FULLTEXT INDEX `ft_search` (`title`,`description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
