-- NetaTrack India: Leaders Table
CREATE TABLE IF NOT EXISTS `leaders` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `photo` VARCHAR(500) DEFAULT NULL,
  `party_id` INT UNSIGNED DEFAULT NULL,
  `state_id` SMALLINT UNSIGNED DEFAULT NULL,
  `constituency` VARCHAR(191) DEFAULT NULL,
  `designation` VARCHAR(191) DEFAULT NULL,
  `position` ENUM('Prime Minister','Chief Minister','Cabinet Minister','MLA','MP','Mayor','Councillor','Governor','Other') NOT NULL DEFAULT 'Other',
  `date_of_birth` DATE DEFAULT NULL,
  `education` VARCHAR(500) DEFAULT NULL,
  `assets_declared` DECIMAL(20,2) DEFAULT NULL,
  `criminal_cases` SMALLINT UNSIGNED DEFAULT 0,
  `terms_served` TINYINT UNSIGNED DEFAULT 0,
  `bio` TEXT DEFAULT NULL,
  `social_twitter` VARCHAR(300) DEFAULT NULL,
  `social_facebook` VARCHAR(300) DEFAULT NULL,
  `social_instagram` VARCHAR(300) DEFAULT NULL,
  `website` VARCHAR(500) DEFAULT NULL,
  -- Scoring fields
  `score_promise_completion` DECIMAL(5,2) DEFAULT 0.00,
  `score_project_delivery` DECIMAL(5,2) DEFAULT 0.00,
  `score_budget_efficiency` DECIMAL(5,2) DEFAULT 0.00,
  `score_public_satisfaction` DECIMAL(5,2) DEFAULT 0.00,
  `score_transparency` DECIMAL(5,2) DEFAULT 0.00,
  `score_corruption_penalty` DECIMAL(5,2) DEFAULT 0.00,
  `score_fake_claims_penalty` DECIMAL(5,2) DEFAULT 0.00,
  `score_verification_trust` DECIMAL(5,2) DEFAULT 0.00,
  `final_score` DECIMAL(5,2) DEFAULT 0.00,
  `rank` ENUM('Excellent','Good','Average','Poor') DEFAULT 'Average',
  `corruption_score` DECIMAL(5,2) DEFAULT 0.00,
  `corruption_level` ENUM('Very Clean','Minor Allegations','Moderate','High Risk') DEFAULT 'Very Clean',
  `score_last_calculated` TIMESTAMP NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `views` INT UNSIGNED DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_leaders_slug` (`slug`),
  INDEX `idx_leaders_party` (`party_id`),
  INDEX `idx_leaders_state` (`state_id`),
  INDEX `idx_leaders_score` (`final_score`),
  CONSTRAINT `fk_leaders_party` FOREIGN KEY (`party_id`) REFERENCES `parties`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_leaders_state` FOREIGN KEY (`state_id`) REFERENCES `states`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
