-- NetaTrack India: Promises Table
CREATE TABLE IF NOT EXISTS `promises` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(500) NOT NULL,
  `slug` VARCHAR(500) NOT NULL UNIQUE,
  `description` TEXT DEFAULT NULL,
  `leader_id` BIGINT UNSIGNED NOT NULL,
  `party_id` INT UNSIGNED DEFAULT NULL,
  `state_id` SMALLINT UNSIGNED DEFAULT NULL,
  `category` ENUM('Healthcare','Education','Infrastructure','Agriculture','Employment','Economy','Security','Environment','Women','Youth','Technology','Other') NOT NULL DEFAULT 'Other',
  `promised_on` DATE DEFAULT NULL,
  `deadline` DATE DEFAULT NULL,
  `source_url` VARCHAR(1000) DEFAULT NULL,
  `source_type` ENUM('Speech','Manifesto','Tweet','Press Release','Parliament','Other') DEFAULT 'Other',
  `status` ENUM('Pending','In Progress','Completed','Broken','Partially Fulfilled','Expired') NOT NULL DEFAULT 'Pending',
  `completion_percentage` TINYINT UNSIGNED DEFAULT 0,
  `ai_confidence` DECIMAL(5,2) DEFAULT NULL COMMENT 'AI confidence score 0-100',
  `ai_summary` TEXT DEFAULT NULL,
  `evidence_url` VARCHAR(1000) DEFAULT NULL,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `verified_by` BIGINT UNSIGNED DEFAULT NULL,
  `verified_at` TIMESTAMP NULL DEFAULT NULL,
  `is_ai_collected` TINYINT(1) NOT NULL DEFAULT 0,
  `views` INT UNSIGNED DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_promises_leader` (`leader_id`),
  INDEX `idx_promises_status` (`status`),
  INDEX `idx_promises_state` (`state_id`),
  INDEX `idx_promises_category` (`category`),
  FULLTEXT INDEX `ft_promises_search` (`title`,`description`),
  CONSTRAINT `fk_promises_leader` FOREIGN KEY (`leader_id`) REFERENCES `leaders`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_promises_party` FOREIGN KEY (`party_id`) REFERENCES `parties`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
