-- NetaTrack India: Government Projects Table
CREATE TABLE IF NOT EXISTS `projects` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(500) NOT NULL,
  `slug` VARCHAR(500) NOT NULL UNIQUE,
  `description` TEXT DEFAULT NULL,
  `state_id` SMALLINT UNSIGNED DEFAULT NULL,
  `district` VARCHAR(100) DEFAULT NULL,
  `leader_id` BIGINT UNSIGNED DEFAULT NULL,
  `party_id` INT UNSIGNED DEFAULT NULL,
  `category` ENUM('Road','Bridge','Hospital','School','Dam','Railway','Power','Water','Housing','IT','Agriculture','Defence','Other') NOT NULL DEFAULT 'Other',
  `budget_allocated` DECIMAL(20,2) DEFAULT NULL,
  `budget_spent` DECIMAL(20,2) DEFAULT NULL,
  `budget_efficiency` DECIMAL(5,2) DEFAULT NULL,
  `start_date` DATE DEFAULT NULL,
  `expected_completion` DATE DEFAULT NULL,
  `actual_completion` DATE DEFAULT NULL,
  `status` ENUM('Announced','Tendered','In Progress','Completed','Delayed','Stalled','Cancelled') NOT NULL DEFAULT 'Announced',
  `progress_percentage` TINYINT UNSIGNED DEFAULT 0,
  `delay_days` INT DEFAULT 0,
  `tender_number` VARCHAR(200) DEFAULT NULL,
  `contractor` VARCHAR(300) DEFAULT NULL,
  `source_url` VARCHAR(1000) DEFAULT NULL,
  `latitude` DECIMAL(10,7) DEFAULT NULL,
  `longitude` DECIMAL(10,7) DEFAULT NULL,
  `ai_summary` TEXT DEFAULT NULL,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `is_ai_collected` TINYINT(1) NOT NULL DEFAULT 0,
  `views` INT UNSIGNED DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_projects_state` (`state_id`),
  INDEX `idx_projects_status` (`status`),
  INDEX `idx_projects_leader` (`leader_id`),
  FULLTEXT INDEX `ft_projects_search` (`title`,`description`),
  CONSTRAINT `fk_projects_state` FOREIGN KEY (`state_id`) REFERENCES `states`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_projects_leader` FOREIGN KEY (`leader_id`) REFERENCES `leaders`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
