-- NetaTrack India: Public Reports / Submissions Table
CREATE TABLE IF NOT EXISTS `public_reports` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `report_type` ENUM('Corruption','Fake Claim','Infrastructure Damage','Project Update','Public Complaint','RTI Document','Other') NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT NOT NULL,
  `state_id` SMALLINT UNSIGNED DEFAULT NULL,
  `district` VARCHAR(100) DEFAULT NULL,
  `leader_id` BIGINT UNSIGNED DEFAULT NULL,
  `project_id` BIGINT UNSIGNED DEFAULT NULL,
  `promise_id` BIGINT UNSIGNED DEFAULT NULL,
  `evidence_photos` JSON DEFAULT NULL,
  `evidence_videos` JSON DEFAULT NULL,
  `evidence_documents` JSON DEFAULT NULL,
  `submitter_name` VARCHAR(191) DEFAULT NULL,
  `submitter_phone` VARCHAR(20) DEFAULT NULL,
  `submitter_email` VARCHAR(191) DEFAULT NULL,
  `is_anonymous` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('Pending','AI Review','Fact Check','Admin Review','Approved','Rejected','Duplicate') NOT NULL DEFAULT 'Pending',
  `ai_spam_score` DECIMAL(5,2) DEFAULT NULL,
  `ai_fake_media_score` DECIMAL(5,2) DEFAULT NULL,
  `ai_verification_notes` TEXT DEFAULT NULL,
  `admin_notes` TEXT DEFAULT NULL,
  `rejected_reason` TEXT DEFAULT NULL,
  `duplicate_of` BIGINT UNSIGNED DEFAULT NULL,
  `reviewed_by` BIGINT UNSIGNED DEFAULT NULL,
  `reviewed_at` TIMESTAMP NULL DEFAULT NULL,
  `published_at` TIMESTAMP NULL DEFAULT NULL,
  `upvotes` INT UNSIGNED DEFAULT 0,
  `downvotes` INT UNSIGNED DEFAULT 0,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_reports_status` (`status`),
  INDEX `idx_reports_type` (`report_type`),
  INDEX `idx_reports_state` (`state_id`),
  INDEX `idx_reports_user` (`user_id`),
  CONSTRAINT `fk_reports_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_reports_state` FOREIGN KEY (`state_id`) REFERENCES `states`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
