-- NetaTrack India: Settings Table
CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `group` VARCHAR(100) NOT NULL DEFAULT 'general',
  `key` VARCHAR(191) NOT NULL,
  `value` LONGTEXT DEFAULT NULL,
  `type` ENUM('string','integer','boolean','json','text','file') NOT NULL DEFAULT 'string',
  `label` VARCHAR(300) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_settings_key` (`group`,`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `settings` (`group`,`key`,`value`,`type`,`label`,`is_public`) VALUES
('general','site_name','NetaTrack India','string','Website Name',1),
('general','site_tagline','Political Transparency & Public Accountability','string','Tagline',1),
('general','site_logo','','file','Site Logo',1),
('general','site_favicon','','file','Favicon',1),
('general','maintenance_mode','0','boolean','Maintenance Mode',0),
('seo','meta_title','NetaTrack India - Track Political Promises','string','Meta Title',1),
('seo','meta_description','Track promises, projects, corruption of Indian politicians','text','Meta Description',1),
('seo','meta_keywords','political transparency, promises, corruption India','string','Meta Keywords',1),
('seo','google_analytics_id','','string','Google Analytics ID',0),
('seo','meta_pixel_id','','string','Meta Pixel ID',0),
('smtp','driver','gmail','string','Mail Driver',0),
('smtp','host','smtp.gmail.com','string','SMTP Host',0),
('smtp','port','587','integer','SMTP Port',0),
('smtp','username','','string','SMTP Username',0),
('smtp','password','','string','SMTP Password',0),
('smtp','from_name','NetaTrack India','string','From Name',0),
('smtp','from_email','','string','From Email',0),
('ai','primary_provider','gemini','string','Primary AI Provider',0),
('ai','openai_key','','string','OpenAI API Key',0),
('ai','gemini_key','','string','Gemini API Key',0),
('ai','sarvam_key','','string','Sarvam AI Key',0),
('ai','openrouter_key','','string','OpenRouter API Key',0),
('scraper','auto_scrape_enabled','1','boolean','Auto Scraping Enabled',0),
('scraper','scrape_interval_minutes','60','integer','Scrape Interval (minutes)',0),
('scraper','ai_confidence_threshold','75','integer','Min AI Confidence %',0),
('theme','dark_mode_default','1','boolean','Dark Mode Default',1),
('theme','primary_color','#6366f1','string','Primary Color',1),
('ads','google_ads_client','','string','Google Ads Client ID',0),
('ads','header_ad_code','','text','Header Ad Code',0),
('ads','sidebar_ad_code','','text','Sidebar Ad Code',0);
